### ISSUE TITLE
Bot crashes when removing a non-existent ban.

### ISSUE THREAD

**Issue by deathspawn** [copygirl/cord#15]
```
[05:42:11]❮▼❯ <snipped> removes ban on *!yes@please.now
[05:42:11]◀━━ Parts: discord (relay@<snipped>) ([ZNC] Relay offline.)
```

```

/home/deathspawn/git/relays/cord/node_modules/irc/lib/irc.js:849
                        throw err;
                        ^

TypeError: Cannot read property 'filter' of undefined
    at chanModes (/home/deathspawn/git/relays/cord/node_modules/irc/lib/irc.js:300:37)
    at /home/deathspawn/git/relays/cord/node_modules/irc/lib/irc.js:319:25
    at Array.forEach (native)
    at Client.<anonymous> (/home/deathspawn/git/relays/cord/node_modules/irc/lib/irc.js:270:26)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at iterator (/home/deathspawn/git/relays/cord/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (native)
    at Socket.handleData (/home/deathspawn/git/relays/cord/node_modules/irc/lib/irc.js:841:15)
    at emitOne (events.js:96:13)

npm ERR! Linux 4.5.5-x86_64-linode69
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! cord@2.2.0 start: `node cord.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cord@2.2.0 start script 'node cord.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cord package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node cord.js
npm ERR! You can get information on how to open an issue for this project with:                                                                                                   npm ERR!     npm bugs cord
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cord
npm ERR! There is likely additional logging output above.
                                                                                                                                                                                  npm ERR! Please include the following file with any support request:
npm ERR!     /home/deathspawn/git/relays/cord/npm-debug.log

```

**Comment by copygirl** [comment]
Oh well, that sucks. It's an issue in the IRC library I'm using I suppose. Not sure if I'll be able to look into that any time soon.
